---
kind: pipeline
type: docker
name: presentation-deploy

steps:
  - name: build
    image: theedgeofrage/sphinx-revealjs-builder

  - name: deploy
    image: plugins/s3
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      bucket: pavle-presentations
      source: _build/revealjs/**/*
      strip_prefix: _build/revealjs/
      target: /serverless
      path_style: true
      endpoint: https://minio.theedgeofrage.com
